config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount ChinaCity::Engine => '/china_city'

  devise_for :admin, controllers: {
  :sessions => "admin/sessions"
  }

  root 'home#index'

  resource :wechat, only: [:show, :create]

  resources :home, only: [:index] do
    get :personal_center,  on: :collection
    get :donations_center, on: :collection
    get :donate_page,      on: :collection
    get :my_address,       on: :collection
  end


  resources :carousels, only: [:detail] do
    get :detail, on: :member
  end

  get 'gybs' => 'gybs#index'
  get 'gybs/append'
  get 'gybs/exchange'

  resources :supports do
    get :detail, on: :collection
  end
  get '/supports/pay/:id', to: 'supports#pay', as: 'support_pay'

  resources :shelf_items
  get '/update_order_address' => 'shelf_items#update_order_address'

  resources :projects do
    member do
      get :detail
    end
  end

  get '/register', to: 'registrations#new'

  resources :donations
  resources :addresses do
    get :modify,      on: :collection
    get :set_default, on: :member
  end

  resources :orders do
    get :cancel_order,           on: :member
    get :apply_refund,           on: :member
    get :confirm_complete,       on: :member
    get :add_gyb_payment_record, on: :collection
    get :get_logistics_info, on: :collection
  end
  get '/orders/pay/:id', to: 'orders#pay', as: 'order_pay'

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      get '/login', to: 'login#index'

      get '/shelf_items', to: 'shelf_items#index'
      get '/shelf_items/get_shelf_item', to: 'shelf_items#get_shelf_item'
      get '/shelf_items/get_linked_project', to: 'shelf_items#get_linked_project'

      get '/projects', to: 'projects#index'
      get '/projects/get_project', to: 'projects#get_project', as: 'get_project'
      get '/projects/get_linked_shelf_items', to: 'projects#get_linked_shelf_items'

      get '/carousels', to: 'carousels#index'

      get '/gybs/get_gyb_income_records', to: 'gybs#get_gyb_income_records'
      get '/gybs/get_gyb_payment_records', to: 'gybs#get_gyb_payment_records'

      get '/addresses/get_addresses', to: 'addresses#get_addresses'
      get '/addresses/get_address', to: 'addresses#get_address'
      get '/addresses/get_default_address', to: 'addresses#get_default_address'
      post '/addresses/create_address', to: 'addresses#create_address'
      delete '/addresses/delete_address', to: 'addresses#delete_address'
      post '/addresses/set_default', to: 'addresses#set_default'
    end
  end

  namespace :admin do
    get 'dashboard' => 'home#index'

    resources :users

    resources :carousels do
      get :preview,   on: :member
      get :publish,   on: :member
      get :depublish, on: :member
    end

    resources :products do
      get :preview, on: :member
    end

    resources :gybs

    resources :shelf_items do
      get :pull_off_shelf,    on: :member
      get :set_recommended,   on: :member
      get :reset_recommended, on: :member
      collection do
        get :on_shelf_list
        get :off_shelf_list
        get :recommended_list
      end
    end

    resources :product_categories
    resources :product_labels

    resources :projects do
      member do
        get :preview
        get :publish
        get :depublish
        get :recommend
        get :reset_recommend
      end
      collection do
        get :all
        get :recommended_projects
        get :get_supports
      end
    end

    resources :donations

    resources :orders do
      collection do
        post :update
        get :query
        get :refund_orders
        get :undelivered_orders
        post :get_excel, :defaults => { :format => 'xlsx' }
      end

      get :refund_process, on: :member
    end
  end

  get '/init_js_info', to: 'init_js_info#init_js_info'

  scope 'wepay' do
    get '/jsapi/',          to: 'wepay#recv'
    get '/unified_order',   to: 'wepay#unified_order'
    get '/refund_order',    to: 'wepay#refund_order'
    get '/init_wx_js_info', to: 'wepay#init_wx_js_info'
    get '/init_jspay_info', to: 'wepay#init_jspay_info'
    get '/get_logistics',   to: 'wepay#get_logistics'
    post '/notify',         to: 'wepay#notify'
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  self.primary_key= 'order_id'
  belongs_to :user
  has_many :order_details, dependent: :destroy

  enum order_status: { REFUND_REJECTED: -5, REFUNDING: -4, REFUNDED: -3, CANCELED: -2, FAILED: -1, UNPAID: 0, PAID: 1 }

  # logistics_status default => 0, so the UNDELIVERED status is implicit.
  # Because it is equivalent to the condition that order_status = 1 AND logistics_status = 0
  enum logistics_status: { DELIVERED: 3, COMPLETED: 4 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AuthenticatedController
  include StatusesHelper

  def query
    respond_to do |format|
      format.html
      format.json { get_rows_with_query_params }
    end
  end

  def get_excel
    @orders = Order.order('created_at DESC').where(wrap_search_obj(params)).joins(:order_details).all
    render xlsx: 'generic_result', disposition: 'attachment', filename: "orders_export_#{Time.now.strftime('%Y%m%d_%H%M%S')}.xlsx"
  end

  def undelivered_orders
    respond_to do |format|
      format.html
      format.json { get_undelivered_rows }
    end
  end

  def refund_orders
    respond_to do |format|
      format.html
      format.json { get_refund_orders_rows }
    end
  end

  def refund_process
    @order_detail = OrderDetail.find_by_order_id(params[:id])
    if @order_detail.note
      @records = @order_detail.note.split('\n')
    end
  end

  def edit
    @order_detail = OrderDetail.find_by_order_id params[:id]
  end

  def update
    order_detail = OrderDetail.find_by_order_id(params[:order_id])
    flag = params[:flag]
    if order_detail.nil?
      render plain: 'failed to find the order.'
    elsif order_detail.order.order_status == 'REFUNDING'
      if flag == '1'
        redirect_to refund_order_path(id: params[:order_id])
      elsif flag == '0'
        note = Time.now.strftime('%Y-%m-%d %T').to_s + ': ' + params[:refusal].to_s + '\n'
        if order_detail.note.nil?
          order_detail.note = note
        else
          order_detail.note += note
        end
        redirect_to refund_orders_admin_orders_path if order_detail.order.update_attribute(:order_status, -5) and order_detail.save
      end
    else
      order_detail.delivery_company = order_detail_params[:delivery_company]
      order_detail.delivery_id      = order_detail_params[:delivery_id]
      if order_detail.save && order_detail.order.update_attribute(:logistics_status, 'DELIVERED')
        redirect_to undelivered_orders_admin_orders_path
      else
        render plain: 'failed to update logistics info.'
      end
    end
  end

  private

  def get_rows_with_query_params
    dt = decode_datatables_params

    search_obj = {
      :include => [],
      :joins => [],
      :order => dt[:sort_statement],
      :conditions => wrap_search_obj(params)
    }

    @total_rows = Order.joins(search_obj[:joins]).where(search_obj[:conditions]).count()
    @rows = Order.page(dt[:page]).per(dt[:per_page])
              .includes(search_obj[:include])
              .joins(search_obj[:joins])
              .order(search_obj[:order])
              .where(search_obj[:conditions])
  end

  def wrap_search_obj(params)
    where_array = []
    where_array << 'user_id=:user_id' unless params['user_id'].blank?
    where_array << 'order_id=:order_id' unless params['order_id'].blank?
    where_array << "logistics_status=:logistics_status AND order_status = '1'" unless params['logistics_status'].blank?
    where_array << 'created_at BETWEEN :start_date AND :end_date' unless params['start_date'].blank? and params['end_date'].blank?

    placeholder_obj = {}
    %w(user_id order_id logistics_status start_date end_date).each {|k| placeholder_obj[k.to_sym] = params[k]}

    [where_array.join(' AND '), placeholder_obj]
  end

  def get_undelivered_rows
    dt = decode_datatables_params

    where_array = []
    where_array << 'orders.order_status = 1 and logistics_status != 3 and logistics_status != 4'

    search_obj = {
        :include => [],
        :joins => [],
        :order => dt[:sort_statement],
        :conditions => [where_array.join(' AND ')]
    }

    @total_rows = Order.count(search_obj)
    @rows = Order.page(dt[:page]).per(dt[:per_page])
                .includes(search_obj[:include])
                .joins(search_obj[:joins])
                .order(search_obj[:order])
                .where(search_obj[:conditions])
  end

  def get_refund_orders_rows
    dt = decode_datatables_params

    where_array = []
    where_array << 'orders.order_status = -4'

    search_obj = {
        :include => [],
        :joins => [],
        :order => dt[:sort_statement],
        :conditions => [where_array.join(' AND ')]
    }

    @total_rows = Order.count(search_obj)
    @rows = Order.page(dt[:page]).per(dt[:per_page])
                .includes(search_obj[:include])
                .joins(search_obj[:joins])
                .order(search_obj[:order])
                .where(search_obj[:conditions])
  end

  def order_detail_params
    params.require(:order_detail).permit(:delivery_company, :delivery_id)
  end

  def order_query_params
    params.require(:order).permit(:user_id, :order_id, :order_status, :start_date, :end_date)
  end
end

app/controllers/orders_controller.rb
class OrdersController < BaseController
  before_filter :check_duplicate_order, only: [:create]
  include StatusesHelper
  include UrlHelper

  def index
    status = params[:status]
    if status == '0'
      @title  = '未完成订单'
      @orders = Order.where('user_id = ? and (order_status = ? or order_status = ?) and logistics_status != ?', current_user.id.to_s, 0, 1, 4).order('created_at DESC')
    elsif status == '1'
      @title  = '已完成订单'
      @orders = Order.where('user_id = ? and logistics_status = ?', current_user.id.to_s, 4).order('created_at DESC')
    elsif status == '2'
      @title  = '退款/售后订单'
      @orders = Order.where('user_id = ? and (order_status = ? or order_status = ? or order_status = ?)', current_user.id.to_s, -3, -4, -5).order('created_at DESC')
    else
      @title  = '所有订单'
      @orders = Order.where('user_id = ?', current_user.id.to_s).order('created_at DESC')
    end
  end

  def pay
    @user         = current_user
    order_id      = params[:id]
    @order_detail = OrderDetail.find_by_order_id order_id
    Address.convert_addr(@order_detail)
  end

  def show
    order_id      = params[:id]
    @order_detail = OrderDetail.find_by_order_id order_id
    Address.convert_addr(@order_detail)
    if @order_detail.note
      @records = @order_detail.note.split('\n')
    end
  end

  def apply_refund
    order_id = params[:id]
    order    = Order.find_by_order_id order_id
    order.update_attribute(:order_status, -4)
    redirect_to orders_path :id => order_id
  end

  def cancel_order
    id    = params[:id]
    order = Order.find_by_order_id id
    order.update_attribute(:order_status, -2)
    redirect_to :action => 'show', :id => id
  end

  def confirm_complete
    id    = params[:id]
    order = Order.find_by_order_id id
    order.update_attribute(:logistics_status, 4)
    redirect_to :action => 'show', :id => id
  end

  def create
    count               = params[:count]
    aid                 = params[:aid]
    siid                = params[:siid]
    remark              = params[:remark]
    shelf_item          = ShelfItem.find_by_id siid
    address             = Address.find_by_id aid
    order_detail_params = shelf_item.attributes.merge(address.attributes)
                              .except('id','project_id', 'product_id', 'product_category_id', 'product_label_id',
                                      'product_detail', 'stock', 'sales', 'is_on_shelf', 'recommended',
                                      'created_at', 'updated_at', 'user_id', 'default', 'category', 'label', 'purpose', 'main_pic')

    # Generate a unique order_id to relate Order with OrderDetail model
    order_id                             = 10000000000 + SecureRandom.random_number(9999999999)
    out_refund_no                        = order_id
    order_detail_params[:shelf_item_id]  = siid
    order_detail_params[:count]          = count.to_i
    order_detail_params[:order_id]       = order_id
    order_detail_params[:out_refund_no]  = out_refund_no
    order_detail_params[:remark]         = remark

    # Determine whether the user has enough gybs for discount and calculate the total price.
    if current_user.gyb < shelf_item.gyb_discount
      order_detail_params[:gyb_discount] = 0
      total_price                        = (order_detail_params[:count] * shelf_item.price) - order_detail_params[:gyb_discount] / 100
    else
      order_detail_params[:gyb_discount] = shelf_item.gyb_discount
      total_price                        = (order_detail_params[:count] * shelf_item.price) - order_detail_params[:gyb_discount] / 100
    end

    order_detail                         = OrderDetail.new order_detail_params
    order_detail.save

    order                = Order.new
    order[:order_id]     = order_id
    order[:user_id]      = current_user.id.to_s
    order[:total_price]  = total_price
    order[:order_status] = '0'
    order.save
    redirect_to :action => 'pay', :id => order_id
  end

  def add_gyb_payment_record
    id                     = params[:id]
    order_detail           = OrderDetail.find_by :order_id => id

    if order_detail.gyb_discount > 0
      gyb_payment          = GybPayment.new
      gyb_payment.user_id  = current_user.id.to_s
      gyb_payment.order_id = order_detail.order_id
      gyb_payment.save

      current_user.gyb     -= order_detail.gyb_discount
      current_user.save
    end
    render json: { status: 'success' }
  end

  def get_logistics_info
    req_data = { "OrderCode": "", "ShipperCode": "SF", "LogisticCode": "118650888018" }.to_json.gsub('"', "'")
    e_business_id = Settings.kdniao.EBusinessID
    req_type = '1002'
    data_sign = Modules::Kdniao.sign_data(req_data)

    uri = Settings.kdniao.APIUrl
    body = {
      RequestData: req_data,
      EBusinessId: e_business_id,
      RequestType: req_type,
      DataSign: data_sign,
      DataType: 2
    }

    info = HTTPClient.post(uri, body: body, header: { 'Content-Type': 'application/json; charset=utf-8' })
    JSON.parse(info.body)
  end

  private
  def check_duplicate_order
    count  = params[:count]
    aid    = params[:aid]
    siid   = params[:siid]
    remark = params[:remark]

    addr         = Address.find_by_id(aid)
    order_detail = OrderDetail.find_by('shelf_item_id = ? and count = ? and remark = ? and province = ? and city = ? and district = ? and detail_address = ?',
                                          siid, count, remark, addr.province, addr.city, addr.district, addr.detail_address)
    if order_detail and order_detail.order.order_status == 'UNPAID'
      flash[:type]    = 'alert'
      flash[:message] = '您有重复的未支付订单, 请前往 我的 -> 未完成订单 进行支付。'
      redirect_to shelf_item_path(params[:siid])
    end
    # render :nothing => true, :status => 301
  end
end

app/views/admin/orders/edit.html.erb
<div class="wrapper-lg">
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading h5">订单查看</div>
        <div class="panel-body">
          <%= render partial: 'form', locals: { url: admin_orders_path } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="nav-content-head">
  <ul class="breadcrumb">
    <li><span class="primary-font"><i class="icon-home"></i></span><a href="/admin/home"> Home</a></li>
    <li>订单管理</li>
    <li>订单查询</li>
  </ul>
</div>

<div class="smart-widget">
  <div class="smart-widget-header">
    <h4>订单查询</h4>
  </div>
  <div class="smart-widget-inner">
    <div class="smart-widget-body">
      <div class="row">
        <%= form_for nil, remote: true, method: :get do |f| %>
          <div class="col-md-2">
            <%= text_field_tag :user_id, nil, class: 'form-control', placeholder: '用户id', data: { :prop => 'user_id' }  %>
          </div>

          <div class="col-md-2">
            <%= text_field_tag :order_id, nil, class: 'form-control', placeholder: '订单编号', data: { :prop => 'order_id' }  %>
          </div>

          <div class="col-md-2">
            <%= select_tag :order_status, "<option value='UNDELIVERED'>UNDELIVERED</option><option value='COMPLETED'>COMPLETED</option><option value='REFUNDED'>REFUNDED</option>", class: 'form-control', prompt: '- 请选择订单状态 -' %>
          </div>

          <div class="col-md-2">
            <%= text_field_tag :start_date, nil, id: 'datetimepicker1', class: 'form-control', placeholder: '起始时间' %>
          </div>

          <div class="col-md-2">
            <%= text_field_tag :end_date, nil, id: 'datetimepicker2', class: 'form-control', placeholder: '结束时间' %>
          </div>

          <div class="col-md-1">
            <%= button_tag '查  询', type: 'button', id: 'query-btn', class: "btn btn-primary" %>
          </div>

          <div class="col-md-1">
            <button class="btn btn-primary">导  出</button>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="wrapper-md">
  <div class="panel panel-default">
    <div class="table-responsive">
      <%= dt id: 'orders_datatable', class: 'table table-striped b-t b-b', :'data-url' => admin_orders_path(:format => :json) do %>
        <%= dt_col(Order.hn(:user_id), data: {data: 'user_id'}) %>
        <%= dt_col(Order.hn(:order_id), data: {data: 'order_id'}) %>
        <%= dt_col(Order.hn(:order_status), data: {data: 'order_status'}) %>
        <%= dt_col(Order.hn(:total_price), data: {data: 'total_price'}) %>
        <%= dt_col(Order.hn(:created_at), data: {data: 'created_at'}) %>
      <% end %>
    </div>
  </div>
</div>

<% content_for :scripts do %>
  <%= controller_js_include %>
<% end %>

app/views/admin/orders/query.html.erb
<div class="nav-content-head">
  <ul class="breadcrumb">
    <li><span class="primary-font"><i class="icon-home"></i></span><a href="/admin/dashboard"> 首页</a></li>
    <li>订单管理</li>
    <li>订单查询</li>
  </ul>
</div>

<div class="smart-widget">
  <div class="smart-widget-header">
    <h4>订单查询</h4>
  </div>
  <div class="smart-widget-inner">
    <div class="smart-widget-body">
      <div class="row">
        <%= form_tag nil, remote: true, method: :get do %>
          <div class="col-md-2">
            <%= text_field_tag :user_id, nil, class: 'form-control filter-input', placeholder: '用户id', data: { :prop => 'user_id' }  %>
          </div>

          <div class="col-md-2">
            <%= text_field_tag :order_id, nil, class: 'form-control filter-input', placeholder: '订单编号', data: { :prop => 'order_id' }  %>
          </div>

          <div class="col-md-2">
            <%= select_tag :logistics_status, "<option value=''>全部</option><option value='0'>待发货</option><option value='3'>已发货</option><option value='4'>已签收</option>", class: 'form-control filter-input', prompt: '- 请选择订单状态 -', data: { :prop => 'logistics_status' } %>
          </div>

          <div class="col-md-2">
            <%= text_field_tag :start_date, nil, id: 'datetimepicker1', class: 'form-control filter-input', placeholder: '起始时间', data: { :prop => 'start_date' } %>
          </div>

          <div class="col-md-2">
            <%= text_field_tag :end_date, nil, id: 'datetimepicker2', class: 'form-control filter-input', placeholder: '结束时间', data: { :prop => 'end_date' } %>
          </div>

          <div class="col-md-2">
            <%= button_tag '查  询', type: 'button', id: 'query-btn', class: "btn btn-primary" %>
            <%= link_to 'javascript:;', class: 'btn btn-primary', id: 'download_xls_btn', data:{ url: get_excel_admin_orders_path(), confirm: '确定导出到Excel?' } do %>
              <i class="fa fa-file-excel-o"></i>&nbsp;导出订单
            <% end %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="wrapper-md">
  <div class="panel panel-default">
    <div class="table-responsive">
      <%= dt id: 'query_orders-datatable', class: 'table table-striped b-t b-b', :'data-url' => query_admin_orders_path(:format => :json) do %>
        <%= dt_col(Order.hn(:user_id), data: {data: 'user_id'}) %>
        <%= dt_col(Order.hn(:order_id), data: {data: 'order_id'}) %>
        <%= dt_col(Order.hn(:order_status), data: {data: 'order_status'}) %>
        <%= dt_col(Order.hn(:total_price), data: {data: 'total_price'}) %>
        <%= dt_col(Order.hn(:created_at), data: {data: 'created_at'}) %>
      <% end %>
    </div>
  </div>
</div>

<% content_for :scripts do %>
  <%= controller_js_include %>
<% end %>

app/views/admin/orders/query_orders.html.erb
<div class="nav-content-head">
  <ul class="breadcrumb">
    <li><span class="primary-font"><i class="icon-home"></i></span><a href="/admin/home"> Home</a></li>
    <li>订单管理</li>
    <li>订单查询</li>
  </ul>
</div>

<div class="smart-widget">
  <div class="smart-widget-header">
    <h4>订单查询</h4>
  </div>
  <div class="smart-widget-inner">
    <div class="smart-widget-body">
      <div class="row">
        <%= form_tag nil, remote: true, method: :get do %>
          <div class="col-md-2">
            <%= text_field_tag :user_id, nil, class: 'form-control filter-input', placeholder: '用户id', data: { :prop => 'user_id' }  %>
          </div>

          <div class="col-md-2">
            <%= text_field_tag :order_id, nil, class: 'form-control filter-input', placeholder: '订单编号', data: { :prop => 'order_id' }  %>
          </div>

          <div class="col-md-2">
            <%= select_tag :order_status, "<option value='2'>未发货</option><option value='3'>已发货</option><option value='4'>已完成</option>", class: 'form-control filter-input', prompt: '- 请选择订单状态 -', data: { :prop => 'order_status' } %>
          </div>

          <div class="col-md-2">
            <%= text_field_tag :start_date, nil, id: 'datetimepicker1', class: 'form-control filter-input', placeholder: '起始时间', data: { :prop => 'start_date' } %>
          </div>

          <div class="col-md-2">
            <%= text_field_tag :end_date, nil, id: 'datetimepicker2', class: 'form-control filter-input', placeholder: '结束时间', data: { :prop => 'end_date' } %>
          </div>

          <div class="col-md-1">
            <%= button_tag '查  询', type: 'button', id: 'query-btn', class: "btn btn-primary" %>
          </div>

          <div class="col-md-1">
            <button class="btn btn-primary">导  出</button>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="wrapper-md">
  <div class="panel panel-default">
    <div class="table-responsive">
      <%= dt id: 'query_orders_datatable', class: 'table table-striped b-t b-b', :'data-url' => query_orders_admin_orders_path(:format => :json) do %>
        <%= dt_col(Order.hn(:user_id), data: {data: 'user_id'}) %>
        <%= dt_col(Order.hn(:order_id), data: {data: 'order_id'}) %>
        <%= dt_col(Order.hn(:order_status), data: {data: 'order_status'}) %>
        <%= dt_col(Order.hn(:total_price), data: {data: 'total_price'}) %>
        <%= dt_col(Order.hn(:created_at), data: {data: 'created_at'}) %>
      <% end %>
    </div>
  </div>
</div>

<% content_for :scripts do %>
  <%= controller_js_include %>
<% end %>

app/views/admin/orders/refund_orders.html.erb
<div class="nav-content-head">
  <ul class="breadcrumb">
    <li><span class="primary-font"><i class="icon-home"></i></span><a href="/admin/dashboard"> 首页</a></li>
    <li>订单管理</li>
    <li>退货退款管理</li>
  </ul>

</div>

<div class="wrapper-md">
  <div class="panel panel-default">
    <div class="table-responsive">
      <%= dt id: 'refund_orders_datatable', class: 'table table-striped b-t b-b', :'data-url' => refund_orders_admin_orders_path(:format => :json) do %>
        <%= dt_col(Order.hn(:user_id), data: { data: 'user_id' }) %>
        <%= dt_col(Order.hn(:order_id), data: { data: 'order_id' }) %>
        <%= dt_col(Order.hn(:order_status), data: { data: 'order_status' }) %>
        <%= dt_col(Order.hn(:total_price), data: { data: 'total_price' }) %>
        <%= dt_col(Order.hn(:created_at), data: { data: 'created_at' }) %>
        <%= dt_col(Order.hn(:actions), data: { data: 'actions' }) %>
      <% end %>
    </div>
  </div>
</div>

<% content_for :scripts do %>
  <%= controller_js_include %>
<% end %>

app/views/admin/orders/refund_process.html.erb
<div class="wrapper-lg">
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading h5">处理退款</div>
        <div class="panel-body">
          <%= render partial: 'form', locals: { url: admin_orders_path } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/orders/undelivered_orders.html.erb
<div class="nav-content-head">
  <ul class="breadcrumb">
    <li><span class="primary-font"><i class="icon-home"></i></span><a href="/admin/dashboard"> 首页</a></li>
    <li>订单管理</li>
    <li>待发货订单</li>
  </ul>

</div>

<div class="wrapper-md">
  <div class="panel panel-default">
    <div class="table-responsive">
      <%= dt id: 'undelivered_orders_datatable', class: 'table table-striped b-t b-b', :'data-url' => undelivered_orders_admin_orders_path(:format => :json) do %>
        <%= dt_col(Order.hn(:user_id), data: {data: 'user_id'}) %>
        <%= dt_col(Order.hn(:order_id), data: {data: 'order_id'}) %>
        <%= dt_col(Order.hn(:order_status), data: {data: 'order_status'}) %>
        <%= dt_col(Order.hn(:total_price), data: {data: 'total_price'}) %>
        <%= dt_col(Order.hn(:created_at), data: {data: 'created_at'}) %>
        <%= dt_col(Product.hn(:action), data: {data: 'actions'}) %>
      <% end %>
    </div>
  </div>
</div>

<% content_for :scripts do %>
  <%= controller_js_include %>
<% end %>