config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount ChinaCity::Engine => '/china_city'

  devise_for :admin, controllers: {
  :sessions => "admin/sessions"
  }

  root 'home#index'

  resource :wechat, only: [:show, :create]

  resources :home, only: [:index] do
    get :personal_center,  on: :collection
    get :donations_center, on: :collection
    get :donate_page,      on: :collection
    get :my_address,       on: :collection
  end


  resources :carousels, only: [:detail] do
    get :detail, on: :member
  end

  get 'gybs' => 'gybs#index'
  get 'gybs/append'
  get 'gybs/exchange'

  resources :supports do
    get :detail, on: :collection
  end
  get '/supports/pay/:id', to: 'supports#pay', as: 'support_pay'

  resources :shelf_items
  get '/update_order_address' => 'shelf_items#update_order_address'

  resources :projects do
    member do
      get :detail
    end
  end

  get '/register', to: 'registrations#new'

  resources :donations
  resources :addresses do
    get :modify,      on: :collection
    get :set_default, on: :member
  end

  resources :orders do
    get :cancel_order,           on: :member
    get :apply_refund,           on: :member
    get :confirm_complete,       on: :member
    get :add_gyb_payment_record, on: :collection
    get :get_logistics_info, on: :collection
  end
  get '/orders/pay/:id', to: 'orders#pay', as: 'order_pay'

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      get '/login', to: 'login#index'

      get '/shelf_items', to: 'shelf_items#index'
      get '/shelf_items/get_shelf_item', to: 'shelf_items#get_shelf_item'
      get '/shelf_items/get_linked_project', to: 'shelf_items#get_linked_project'

      get '/projects', to: 'projects#index'
      get '/projects/get_project', to: 'projects#get_project', as: 'get_project'
      get '/projects/get_linked_shelf_items', to: 'projects#get_linked_shelf_items'

      get '/carousels', to: 'carousels#index'

      get '/gybs/get_gyb_income_records', to: 'gybs#get_gyb_income_records'
      get '/gybs/get_gyb_payment_records', to: 'gybs#get_gyb_payment_records'

      get '/addresses/get_addresses', to: 'addresses#get_addresses'
      get '/addresses/get_address', to: 'addresses#get_address'
      get '/addresses/get_default_address', to: 'addresses#get_default_address'
      post '/addresses/create_address', to: 'addresses#create_address'
      delete '/addresses/delete_address', to: 'addresses#delete_address'
      post '/addresses/set_default', to: 'addresses#set_default'
    end
  end

  namespace :admin do
    get 'dashboard' => 'home#index'

    resources :users

    resources :carousels do
      get :preview,   on: :member
      get :publish,   on: :member
      get :depublish, on: :member
    end

    resources :products do
      get :preview, on: :member
    end

    resources :gybs

    resources :shelf_items do
      get :pull_off_shelf,    on: :member
      get :set_recommended,   on: :member
      get :reset_recommended, on: :member
      collection do
        get :on_shelf_list
        get :off_shelf_list
        get :recommended_list
      end
    end

    resources :product_categories
    resources :product_labels

    resources :projects do
      member do
        get :preview
        get :publish
        get :depublish
        get :recommend
        get :reset_recommend
      end
      collection do
        get :all
        get :recommended_projects
        get :get_supports
      end
    end

    resources :donations

    resources :orders do
      collection do
        post :update
        get :query
        get :refund_orders
        get :undelivered_orders
        post :get_excel, :defaults => { :format => 'xlsx' }
      end

      get :refund_process, on: :member
    end
  end

  get '/init_js_info', to: 'init_js_info#init_js_info'

  scope 'wepay' do
    get '/jsapi/',          to: 'wepay#recv'
    get '/unified_order',   to: 'wepay#unified_order'
    get '/refund_order',    to: 'wepay#refund_order'
    get '/init_wx_js_info', to: 'wepay#init_wx_js_info'
    get '/init_jspay_info', to: 'wepay#init_jspay_info'
    get '/get_logistics',   to: 'wepay#get_logistics'
    post '/notify',         to: 'wepay#notify'
  end
end

app/models/shelf_item.rb
class ShelfItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :project

  has_many :order_details

  mount_uploader :thumb, ShelfItemThumbUploader
  mount_uploader :main_pic, ShelfItemMainPicUploader
end

app/controllers/admin/shelf_items_controller.rb
class Admin::ShelfItemsController < Admin::AuthenticatedController
  def off_shelf_list
    respond_to do |format|
      format.html
      format.json { get_rows }
    end
  end

  def on_shelf_list
    respond_to do |format|
      format.html
      format.json { get_rows_from_shelf }
    end
  end

  def recommended_list
    respond_to do |format|
      format.html
      format.json { get_rows_from_recommended_list }
    end
  end

  def edit
    @shelf_item = ShelfItem.new
    id =  params[:id]
    @product = Product.find_by :id => id
    render 'form', :layout =>  'bootstrap_modal'
  end

  def create
    id = params[:id]
    if ShelfItem.find_by :id => id
      create_or_update id, shelf_item_params
    else
      create_or_update 0, shelf_item_params
    end
  end

  def set_recommended
    id = params[:id]
    shelf_item = ShelfItem.find_by_id(id)

    if shelf_item && shelf_item.recommended != '1'
      shelf_item.recommended = '1'
      shelf_item.save
      redirect_to on_shelf_list_admin_shelf_items_path
    else
      render json: {data: 'Oops~ something is wrong'}
    end
  end

  def reset_recommended
    id = params[:id]
    shelf_item = ShelfItem.find_by_id(id)
    shelf_item.recommended = '0'
    shelf_item.save

    redirect_to recommended_list_admin_shelf_items_path
  end

  def pull_off_shelf
    id = params[:id]
    product = Product.find_by :id => id
    shelf_item = ShelfItem.find_by :id => id
    shelf_item.update_attributes(:is_on_shelf => '0', :recommended => '0')
    product.update_attribute(:is_on_shelf, '0')
    redirect_to on_shelf_list_admin_shelf_items_path
  end

  private
  def get_rows
    dt = decode_datatables_params
    where_array = []
    where_array << "products.is_on_shelf = '0'"

    search_obj = {
        :include => [],
        :joins => [],
        :order => dt[:sort_statement],
        :conditions => [where_array.join(' AND ')]
    }

    @total_rows = Product.count(search_obj)
    @rows = Product.page(dt[:page]).per(dt[:per_page])
                .includes(search_obj[:include])
                .joins(search_obj[:joins])
                .order(search_obj[:order])
                .where(search_obj[:conditions])
  end

  def get_rows_from_shelf
    dt = decode_datatables_params
    where_array = []
    where_array << "shelf_items.is_on_shelf = '1'"

    search_obj = {
        :include => [],
        :joins => [],
        :order => dt[:sort_statement],
        :conditions => [where_array.join(' AND ')]
    }

    @total_rows = ShelfItem.count(search_obj)
    @rows = ShelfItem.page(dt[:page]).per(dt[:per_page])
                .includes(search_obj[:include])
                .joins(search_obj[:joins])
                .order(search_obj[:order])
                .where(search_obj[:conditions])

  end

  def get_rows_from_recommended_list
    dt = decode_datatables_params
    where_array = []
    where_array << "shelf_items.is_on_shelf = '1' and shelf_items.recommended = '1'"

    search_obj = {
        :include => [],
        :joins => [],
        :order => dt[:sort_statement],
        :conditions => [where_array.join(' AND ')]
    }

    @total_rows = ShelfItem.count(search_obj)
    @rows = ShelfItem.page(dt[:page]).per(dt[:per_page])
                .includes(search_obj[:include])
                .joins(search_obj[:joins])
                .order(search_obj[:order])
                .where(search_obj[:conditions])

  end

  def create_or_update(id, form_data)
    if id == 0
      product = Product.find_by :id => params[:id]
      merged_data = product.attributes.merge form_data
      shelf_item = ShelfItem.new merged_data
      shelf_item.is_on_shelf = '1'
      shelf_item.thumb = product.thumb
      shelf_item.main_pic = product.main_pic
      product.is_on_shelf = '1'
      product.save
      shelf_item.save
    else
      product = Product.find_by :id => params[:id]
      product.is_on_shelf = '1'
      product.save
      shelf_item = ShelfItem.find_by :id => params[:id]
      data = product.attributes.merge form_data
      shelf_item.is_on_shelf = '1'
      shelf_item.thumb = product.thumb
      shelf_item.main_pic = product.main_pic
      shelf_item.update_attributes data
    end
    # response_after_save_json result, @shelf_item
    redirect_to off_shelf_list_admin_shelf_items_path
  end

  def shelf_item_params
    params.require(:shelf_item).permit(:price, :gyb_discount, :stock)
  end
end

app/controllers/api/v1/shelf_items_controller.rb
class Api::V1::ShelfItemsController < ApplicationController
  def index
    param = params[:param]
    if param == 'recommended'
      shelf_items = ShelfItem.where('is_on_shelf = ? and recommended = ?', '1', '1')
      render json: shelf_items, status: :ok
    else
      shelf_items = ShelfItem.where('is_on_shelf = ?', '1')
      render json: shelf_items, status: :ok
    end
  end

  def get_shelf_item
    id = params[:id]
    shelf_item = ShelfItem.find_by(:id => id)
    render json: shelf_item, status: :ok if shelf_item
  end

  def get_linked_project
    siid = params[:siid]
    shelf_item = ShelfItem.find_by_id(siid)
    if shelf_item
      project = shelf_item.project
      render json: project, status: :ok if project
    else
      render json: { result: 'FAIL' }
    end
  end
end

app/controllers/shelf_items_controller.rb
class ShelfItemsController < BaseController
  def index
    @shelf_items = ShelfItem.where(:is_on_shelf => '1').order('updated_at DESC')
  end

  def show
    @shelf_item = ShelfItem.find_by(:id => params[:id])
    pid         = params[:pid]

    if pid.nil?
      @project = Project.find_by(:project_id => @shelf_item.project_id, :is_published => '1')
    else
      @project = Project.find_by(:project_id => pid, :is_published => '1')
    end

    addresses = Address.where(user_id: current_user.id.to_s)
    if addresses != []
      addresses.each do |ele|
        if ele.default == '1'
          @address = ele
          break
        else
          @address = addresses.last
        end
      end
    end

    if @address
      Address.convert_addr(@address)
    end
  end

  def update_order_address
    _addresses = Address.where('user_id = ?', current_user.id.to_s)
    if _addresses != []
      _addresses.each do |_addr|
        Address.convert_addr(_addr)
      end
    end

    respond_to do |format|
      format.js { render :update_order_address, locals: { addresses: _addresses } }
    end
  end
end

app/views/shelf_items/_address_list.html.erb
<div id="my-address" class="my-address">

  <% if addresses == [] %>
    <div class="buttons">
      <button id="add-address-btn" class="btn btn-default btn-highlight p-t p-b m-t">添加地址</button>
    </div>
  <% else %>
    <% addresses.each do |addr| %>
      <div class="address-item p-l p-r p-t p-b">
        <div id="address-info" class="address-info" data-id="<%= addr.id %>">
          <p class="name"><%= addr.receiver_name %></p>
          <p class="tel"><%= addr.mobile %></p>
          <p class="address"><%= "#{ addr.province.to_s }#{' '}#{ addr.city.to_s }#{' '}#{ addr.district.to_s }#{' '}#{ addr.detail_address.to_s }" %></p>
        </div>
        <!--<div class="buttons">-->
          <%#= link_to set_default_address_path(addr.id), :method => 'get', :'data-confirm' => '确定设置为默认地址吗？', :class => 't-left set-default-btn' do %>
            <%# if addr.default == '1' %>
              <!--<i class="fa fa-check-square fa-lg default"></i>&nbsp;已设为默认-->
            <%# else %>
              <!--<i class="fa fa-check-square fa-lg"></i>&nbsp;设为默认-->
            <%# end %>
          <%# end %>
          <%#= link_to address_path(addr.id), :method => 'delete', :'data-confirm' => '确定删除嘛？', :class => 't-right delete-btn p-l' do %>
            <!--<i class="fa fa-trash fa-lg"></i>&nbsp;删除-->
          <%# end %>
          <!--<a href="javascript:;" data-id="<%#= addr.id %>" class="t-right edit-btn"><i class="fa fa-edit fa-lg"></i>&nbsp;编辑</a>-->
          <div class="clear"></div>
        <!--</div>-->
      </div>
    <% end %>

    <!--<div class="buttons">-->
      <!--<button id="add-address-btn" class="btn btn-default btn-highlight p-t p-b m-t">添加地址</button>-->
    <!--</div>-->
    <% end %><!-- if end -->
</div>

app/views/shelf_items/index.html.erb
<div class="shelf-items-wrapper">
  <ul class="shelf-items-list">
    <% @shelf_items.each do |p| %>
      <%= link_to shelf_item_path p.id do %>
        <li class="item">
          <%= image_tag p.thumb.to_s %>
          <div class="item-property p-b">
            <div class="item-name">
              <%= p.product_name.to_s %>
            </div>
            <div class="item-bottom">
              <div class="item-price red">
                ¥<%= '%.2f' % p.price.to_s %>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

<%= render template: 'shared/tabs' %>

<% content_for :title, set_title('GOODBUY公益商城 | 好物') %>

<script>
  $(document).ready(function () {
    var host_url     =  'http://' + window.location.href.split('//')[1].split('/')[0] + '/';
    var current_url  = host_url + 'shelf_items';

    wx.ready(function () {
      wx.onMenuShareTimeline({
        title: 'GOODBUY公益商城', // 分享标题
        link: current_url,
        imgUrl: host_url + 'logo.png', // 分享图标
        success: function () {
          // 用户确认分享后执行的回调函数
        },
        cancel: function () {
          // 用户取消分享后执行的回调函数
        }
      });

      wx.onMenuShareAppMessage({
        title: 'GOODBUY公益商城', // 分享标题
        desc: '快来看看优秀的公益项目和创意新潮的产品吧', // 分享描述
        link: current_url,
        imgUrl: host_url + 'logo.png', // 分享图标
        type: '', // 分享类型,music、video或link，不填默认为link
        dataUrl: '', // 如果type是music或video，则要提供数据链接，默认为空
        success: function () {
          // 用户确认分享后执行的回调函数
        },
        cancel: function () {
          // 用户取消分享后执行的回调函数
        }
      });
    });
  })
</script>

app/views/shelf_items/show.html.erb
<div id="overlay"></div>
<div class="<%= flash[:type] %>" id="alert-box">
  <p><%= flash[:message] %></p>
</div>
<% if @project %>
  <div class="project-overview p-l p-r p-t p-b">
    <div class="p-thumb">
      <%= image_tag @project.thumb %>
    </div>
    <div class="p-title p-l p-r">
      <%= @project.project_name.to_s %>
    </div>
    <div class="p-btn m-r">
      <%= button_to '前去看看', { :controller => 'projects', :action => 'detail', :id => @project.id }, :method => 'get', :class => 'btn btn-default btn-highlight p-t p-b' %>
    </div>
  </div>
<% end %>

<div class="shelf-item-detail">
  <div class="big-thumb">
    <%= image_tag @shelf_item.main_pic %>
  </div>

  <div class="main">
    <div class="main-left">
      <div class="product-name">
        <%= @shelf_item.product_name.to_s %>
      </div>
      <div class="price">
        <span class="big-price">￥<%= '%.2f' % @shelf_item.price %></span>
        <!--<span class="coin"><%#= @shelf_item.gyb_discount.to_i %>&nbsp;公益币</span>-->
      </div>

      <!--<div class="info">-->
      <!--<dl class="dl-clear">-->
      <!--<dt>销量：</dt>-->
      <!--<dd>20件</dd>-->
      <!--</dl>-->

      <!--<dl class="dl-clear">-->
      <!--<dt>好评：</dt>-->
      <!--<dd>100%</dd>-->
      <!--</dl>-->

      <!--<dl class="dl-clear">-->
      <!--<dt>数量：</dt>-->
      <!--<dd>100</dd>-->
      <!--</dl>-->
      <!--<p class="stock">（库存1000件）</p>-->

      <!--</div>-->

      <!--<div class="count"></div>-->
      <!--</div>-->

      <!--<div class="main-right">-->
      <!--<ul class="attrs">-->
      <!--<li>包邮</li>-->
      <!--<li>可使用公益币</li>-->
      <!--<li>可获得公益币</li>-->
      <!--<li>公益项目</li>-->
      <!--</ul>-->
      <!--</div>-->
      <!--</div>-->

      <!--<div class="nav">-->
      <!--<ul>-->
      <!--<li><%#= link_to '商品详情', 'javascript:;', class: 'detail' %></li>-->
      <!--<span class="split"></span>-->
      <!--<li><%#= link_to '评论', '#', class: 'comments' %></li>-->
      <!--</ul>-->
      <!--</div>-->
    </div>
    <div class="clear"></div>
  </div>

  <div class="detail-body p-t">
    <%= @shelf_item.product_detail.to_s.html_safe %>
  </div>
</div>

<% if @shelf_item.purpose == '2' %>
  <div class="shelf-item-bottom">
    <div class="buttons">
      <div class="btn-default other-btn p-t p-b">
        <%= link_to root_path do %>
          <i class="fa fa-home fa-lg"></i>&nbsp;&nbsp;首页
        <% end %>
      </div>
      <div class="btn-default other-btn p-t p-b">
        <%= link_to personal_center_home_index_path do %>
          <i class="fa fa-user fa-lg"></i>&nbsp;&nbsp;我的
        <% end %>
      </div>
      <div id="buy-btn" class="btn-default btn-highlight buy-btn p-t p-b">立即购买</div>
      <!--<button id="cart-btn" class="btn btn-default p-t p-b">加入购物车</button>-->
    </div>
  </div>

  <% if @address.nil? %>
    <div class="confirm-box" id="confirm-box">
      <div id="btn-close">
        <span>x</span>
      </div>
      <%= link_to 'javascript:;' do %>
        <button id="add-address-btn" class="btn btn-default btn-highlight m-l m-r m-t p-t p-b">添加地址</button>
      <% end %>
      <div class="item-number" data-trigger="spinner" id="spinner">
        <p>购买数量：</p>
        <a href="javascript:;" data-spin="down" class="t-minus">-</a>
        <%= text_field_tag :count, '1', class: 'count', data: {rule: 'quantity', max: '10'} %>
        <a href="javascript:;" data-spin="up" class="t-plus">+</a>
      </div>
      <div class="remark">
        <p>备注：</p>
        <%= text_field_tag :remark, '', class: 'light-border', placeholder: '限20字，可不填。', size: '35', maxlength: '20' %>
      </div>
      <div class="buttons">
        <%= submit_tag '确定提交', id: 'confirm-btn', disabled: true, class: 'btn btn-default btn-highlight btn-middle btn-disabled m-l m-r p-t p-b' %>
      </div>
    </div>
  <% else %>
    <div class="confirm-box" id="confirm-box">
      <div id="btn-close">
        <span>x</span>
      </div>
      <%= form_tag '/orders', method: :post do %>
        <%#= link_to shelf_items_update_order_address_path, remote: true do %>
        <div id="delivery-addr-wrapper" class="delivery-addr-wrapper">
          <div class="delivery-addr">
            <p class="name inline-block"><%= @address.receiver_name.to_s %></p>
            <p class="tel inline-block"><%= @address.mobile.to_s %></p>
            <p class="address"><%= @address.province.to_s + ' ' + @address.city.to_s + ' ' + @address.district.to_s + ' ' + @address.detail_address.to_s %></p>
          </div>
          <div class="more">
            <i class="fa fa-angle-right fa-2x"></i>
          </div>
        </div>
        <%# end %>

        <div class="item-number" data-trigger="spinner" id="spinner">
          <p>购买数量：</p>
          <a href="javascript:;" data-spin="down" class="t-minus">-</a>
          <%= number_field_tag :count, '1', class: 'count', data: {rule: 'quantity'} %>
          <a href="javascript:;" data-spin="up" class="t-plus">+</a>
        </div>
        <div class="remark">
          <p>备注：</p>
          <%= text_field_tag :remark, '', class: 'light-border', placeholder: '限20字，可不填。', size: '35', maxlength: '20' %>
        </div>
        <%= hidden_field_tag 'aid', @address.id %>
        <%= hidden_field_tag 'siid', @shelf_item.id %>
        <div class="buttons">
          <%= submit_tag '确定提交', id: 'confirm-btn', data: { disable_with: '正在下单...' }, class: 'btn btn-default btn-highlight btn-middle m-l m-r p-t p-b' %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div id="address-list" class="address-list"></div>

  <%= hidden_field_tag 'shelf_item_title', @shelf_item.product_name %>
  <%= hidden_field_tag 'shelf_item_thumb', @shelf_item.thumb %>
  <%= hidden_field_tag 'shelf_item_id', @shelf_item.id %>

<% else %>
  <div class="shelf-item-bottom">
    <div class="buttons">
      <div class="btn-default other-btn p-t p-b">
        <%= link_to root_path do %>
          <i class="fa fa-home fa-lg"></i>&nbsp;&nbsp;首页
        <% end %>
      </div>
      <div class="btn-default other-btn p-t p-b">
        <%= link_to personal_center_home_index_path do %>
          <i class="fa fa-user fa-lg"></i>&nbsp;&nbsp;我的
        <% end %>
      </div>
      <div id="buy-btn" class="btn-default btn-highlight buy-btn p-t p-b">购买支持</div>
      <!--<button id="cart-btn" class="btn btn-default p-t p-b">加入购物车</button>-->
    </div>
  </div>

  <div class="confirm-box" id="confirm-box">
    <div id="btn-close">
      <span>x</span>
    </div>
    <%= form_tag '/supports', method: :post do %>
      <div class="item-number m-t" data-trigger="spinner" id="spinner">
        <p>支持数量：</p>
        <a href="javascript:;" data-spin="down" class="t-minus">-</a>
        <%= number_field_tag :count, '1', class: 'count', data: {rule: 'quantity'} %>
        <a href="javascript:;" data-spin="up" class="t-plus">+</a>
      </div>
      <div class="remark">
        <p>备注：</p>
        <%= text_field_tag :remark, '', class: 'light-border', placeholder: '限20字，可不填。', size: '35', maxlength: '20' %>
      </div>
      <%= hidden_field_tag 'pid', @shelf_item.project.project_id %>
      <%= hidden_field_tag 'type', '1' %>
      <%= hidden_field_tag 'siid', @shelf_item.id %>
      <div class="buttons">
        <%= submit_tag '确定提交', id: 'confirm-btn', data: { disable_with: '正在下单...' }, class: 'btn btn-default btn-highlight btn-middle m-l m-r p-t p-b' %>
      </div>
    <% end %>
  </div>
<% end %>

<% content_for :title, set_title('商品详情') %>

<script>
  $(document).ready(function () {
    setTimeout(function () {
      $('.alert').fadeOut('slow', function () {
        $('#alert-box').removeClass('alert');
      })
    }, 3500);
    
    $('#add-address-btn').on('click', function () {
      $.ajax({
        method: 'get',
        url: '/addresses/new',
        remote: 'true',
        success: function (res) {
          $('#overlay').fadeIn('fast', function () {
            $('#overlay').fadeIn('fast', function () {
              $('body').append('<div id="add-address-form" class="address-form"></div>');
              $('#add-address-form').append(res).fadeIn('fast');
              $('.city-group').china_city();
            })
          })
        }
      })
    });

    $('body').on('click', '#cancel-btn', function () {
      $('.address-form').fadeOut('fast', function () {
        $('#add-address-form').fadeOut().remove();
      });
    });

    $('body').on('click', '#save-address', function (check) {
      var receiver_name  = document.getElementById('receiver_name').value;
      var mobile         = document.getElementById('mobile').value;
      var province       = document.getElementById('province').value;
      var city           = document.getElementById('city').value;
      var district       = document.getElementById('district').value;
      var detail_address = document.getElementById('detail_address').value;

      isFilledProperly = true;

      if (receiver_name == '') {
        alert('请填写收货人姓名！');
        isFilledProperly = false;
      }

      if (!checkPhone(mobile)) {
        alert('手机号码有误，请检查！');
        isFilledProperly = false;
      }

      if (province == "--省份--" || city == "--城市--" || district == "--区域--") {
        alert('请检查省市区是否已选择！');
        isFilledProperly = false;
      }

      if (detail_address == '') {
        alert('请填写详细地址！');
        isFilledProperly = false;
      }

      if (!isFilledProperly) {
        check.preventDefault();
      }
    });

    function checkPhone(mobile){
      return (/^1[34578]\d{9}$/.test(mobile));
    }

    $('confirm-btn').on('click', function (check) {
      var count = $('#count').val();
      alert(count);
      if (isNum(count)) {
        check.preventDefault();
        alert('数量只能为数字!');
      }

      function isNum(input) {
        return (/^[0-9]*$ /.test(input));
      }
    });

    $('#buy-btn').on('click', function () {
      $('#overlay').fadeIn('fast', function () {
        $('#confirm-box').animate({height: 'toggle'}, 'fast')
      })
    });

    $('#overlay').on('click', function () {
      $('#confirm-box').animate({height: 'toggle'}, 'fast', function () {
        $('#add-address-form').fadeOut().remove();
        $('#overlay').fadeOut('fast')
      })
    });

    $('#btn-close').on('click', function () {
      $('#confirm-box').animate({height: 'toggle'}, 'fast', function () {
        $('#add-address-form').fadeOut().remove();
        $('#overlay').fadeOut('fast')
      })
    });

    $('#delivery-addr-wrapper').on('click', function () {
      $.ajax({
        method: 'get',
        url: '/update_order_address',
        success: function () {
          $('#address-list').toggle('fast');
        }
      })
    });

    $('#address-list').on('click', '#address-info', function () {
      var id      = $(this).data('id');
      var name    = $(this).children('p.name').html();
      var tel     = $(this).children('p.tel').html();
      var address = $(this).children('p.address').html();

      var delivery_address = $('#delivery-addr-wrapper');

      $('#aid').val(id);
      delivery_address.find('.name').text(name);
      delivery_address.find('.tel').text(tel);
      delivery_address.find('.address').text(address);

      $('#address-list').toggle('fast');
    });

    wx.ready(function () {
      var shelf_item_id = document.getElementById('shelf_item_id').value;
      var current_url   = window.location.href.split('shelf_items')[0] + 'shelf_items/' + shelf_item_id;
      var host_url      = 'http://' + current_url.split('//')[1].split('/')[0] + '/';
      var shelf_item_title = document.getElementById('shelf_item_title').value;
      var shelf_item_thumb = document.getElementById('shelf_item_thumb').value;

      wx.onMenuShareTimeline({
        title: shelf_item_title, // 分享标题
        link: current_url,
        imgUrl: host_url + shelf_item_thumb, // 分享图标
        success: function () {
            // 用户确认分享后执行的回调函数
        },
        cancel: function () {
            // 用户取消分享后执行的回调函数
        }
      });

      wx.onMenuShareAppMessage({
        title: shelf_item_title, // 分享标题
        desc: shelf_item_title, // 分享描述
        link: current_url,
        imgUrl: host_url + shelf_item_thumb, // 分享图标
        type: '', // 分享类型,music、video或link，不填默认为link
        dataUrl: '', // 如果type是music或video，则要提供数据链接，默认为空
        success: function () {
            // 用户确认分享后执行的回调函数
        },
        cancel: function () {
            // 用户取消分享后执行的回调函数
        }
      });
    })
  })
</script>

app/views/shelf_items/update_order_address.js.erb
$('#address-list').html("<%= j (render partial: 'address_list', locals: { addresses: addresses }) %>");