config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount ChinaCity::Engine => '/china_city'

  devise_for :admin, controllers: {
  :sessions => "admin/sessions"
  }

  root 'home#index'

  resource :wechat, only: [:show, :create]

  resources :home, only: [:index] do
    get :personal_center,  on: :collection
    get :donations_center, on: :collection
    get :donate_page,      on: :collection
    get :my_address,       on: :collection
  end


  resources :carousels, only: [:detail] do
    get :detail, on: :member
  end

  get 'gybs' => 'gybs#index'
  get 'gybs/append'
  get 'gybs/exchange'

  resources :supports do
    get :detail, on: :collection
  end
  get '/supports/pay/:id', to: 'supports#pay', as: 'support_pay'

  resources :shelf_items
  get '/update_order_address' => 'shelf_items#update_order_address'

  resources :projects do
    member do
      get :detail
    end
  end

  get '/register', to: 'registrations#new'

  resources :donations
  resources :addresses do
    get :modify,      on: :collection
    get :set_default, on: :member
  end

  resources :orders do
    get :cancel_order,           on: :member
    get :apply_refund,           on: :member
    get :confirm_complete,       on: :member
    get :add_gyb_payment_record, on: :collection
    get :get_logistics_info, on: :collection
  end
  get '/orders/pay/:id', to: 'orders#pay', as: 'order_pay'

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      get '/login', to: 'login#index'

      get '/shelf_items', to: 'shelf_items#index'
      get '/shelf_items/get_shelf_item', to: 'shelf_items#get_shelf_item'
      get '/shelf_items/get_linked_project', to: 'shelf_items#get_linked_project'

      get '/projects', to: 'projects#index'
      get '/projects/get_project', to: 'projects#get_project', as: 'get_project'
      get '/projects/get_linked_shelf_items', to: 'projects#get_linked_shelf_items'

      get '/carousels', to: 'carousels#index'

      get '/gybs/get_gyb_income_records', to: 'gybs#get_gyb_income_records'
      get '/gybs/get_gyb_payment_records', to: 'gybs#get_gyb_payment_records'

      get '/addresses/get_addresses', to: 'addresses#get_addresses'
      get '/addresses/get_address', to: 'addresses#get_address'
      get '/addresses/get_default_address', to: 'addresses#get_default_address'
      post '/addresses/create_address', to: 'addresses#create_address'
      delete '/addresses/delete_address', to: 'addresses#delete_address'
      post '/addresses/set_default', to: 'addresses#set_default'
    end
  end

  namespace :admin do
    get 'dashboard' => 'home#index'

    resources :users

    resources :carousels do
      get :preview,   on: :member
      get :publish,   on: :member
      get :depublish, on: :member
    end

    resources :products do
      get :preview, on: :member
    end

    resources :gybs

    resources :shelf_items do
      get :pull_off_shelf,    on: :member
      get :set_recommended,   on: :member
      get :reset_recommended, on: :member
      collection do
        get :on_shelf_list
        get :off_shelf_list
        get :recommended_list
      end
    end

    resources :product_categories
    resources :product_labels

    resources :projects do
      member do
        get :preview
        get :publish
        get :depublish
        get :recommend
        get :reset_recommend
      end
      collection do
        get :all
        get :recommended_projects
        get :get_supports
      end
    end

    resources :donations

    resources :orders do
      collection do
        post :update
        get :query
        get :refund_orders
        get :undelivered_orders
        post :get_excel, :defaults => { :format => 'xlsx' }
      end

      get :refund_process, on: :member
    end
  end

  get '/init_js_info', to: 'init_js_info#init_js_info'

  scope 'wepay' do
    get '/jsapi/',          to: 'wepay#recv'
    get '/unified_order',   to: 'wepay#unified_order'
    get '/refund_order',    to: 'wepay#refund_order'
    get '/init_wx_js_info', to: 'wepay#init_wx_js_info'
    get '/init_jspay_info', to: 'wepay#init_jspay_info'
    get '/get_logistics',   to: 'wepay#get_logistics'
    post '/notify',         to: 'wepay#notify'
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::AuthenticatedController
  def index
    @num_undelivered_orders = Order.where('order_status = ? and logistics_status != ? and logistics_status != ?', 1, 3, 4).count
    @num_refunding_orders   = Order.where('order_status = ?', -4).count
    @sales_volume           = Order.where('order_status = ? and created_at between ? and ?', 1, Time.new.change(hour: 0), Time.now).sum(:total_price)
    @num_new_users          = User.where('created_at between ? and ?', Time.new.change(hour: 0), Time.now).count
    @num_supports           = Support.where('status = ?', '1').count
  end
end

app/controllers/home_controller.rb
class HomeController < BaseController
  def index
    @recommended_items = ShelfItem.where("recommended = '1'").order('updated_at DESC')
    @projects          = Project.where('is_published = ? and is_recommended = ?', '1', '1').order('updated_at DESC')
    @carousels         = Carousel.where('is_published = ?', '1').order('updated_at DESC').first(3)
  end

  def personal_center
    @user = current_user
  end

  def donations_center
  end

  def project_detail
  end

  def product_detail
  end

  def donate_page
  end

  def my_address
  end
end

app/views/home/donate_page.html.erb
<div class="donate-page" id="donate-page">
  <div class="donate-page-head">
    <%= image_tag 'donation_bgp.png' %>
  </div>

  <div class="donation-info m-t">
    <%= form_tag("/submit_donation_info", method: "get") do %>
      <div class="form-group">
        <%= label_tag '物品属类' %>
        <%= select_tag '物品属类', options_for_select([ "类别1", "类别2" ], "类别1"), :class => 'form-control' %>
      </div>
      <div class="form-group">
        <%= label_tag '物品名称' %>
        <%= text_field_tag(:donation_cate, nil, :class => 'form-control') %>
      </div>

      <div class="form-group">
        <%= label_tag '物品描述' %>
        <%= text_field_tag(:donation_desc, nil, :class => 'form-control') %>
      </div>

      <div class="form-group">
        <%= label_tag '物流公司' %>
        <%= select_tag '物流公司', options_for_select([ "类别1", "类别2" ], "类别1"), :class => 'form-control' %>
      </div>

      <div class="form-group">
        <%= label_tag '单号' %>
        <%= text_field_tag(:delivery_num, nil, :class => 'form-control') %>
      </div>

      <div class="form-group">
        <%= label_tag '上传照片' %>
        <div class="donation-photos m-t p-l">
          <div class="camera">
            <i class="fa fa-plus fa-lg"></i>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= submit_tag("提交", :class => 'form-control' ) %>
      </div>
    <% end %>
  </div>

</div>

app/views/home/donations_center.html.erb
<div class="donations-center" id="donations-center">
  <div class="donation-head"></div>

  <div class="donate-btn m-r m-l" id="donate-btn">
    <p>我要捐赠</p>
  </div>

  <div class="remarks m-t m-b p-t p-b">
    <p>你还没有捐赠过物品哦~</p>
    <p>点击上方按钮前往捐赠吧~</p>
  </div>

  <div class="history-donations" id="history-donations">
    <div class="donation s-s p-t p-b p-l p-r">
      <div class="donation-pic ">
        <%= image_tag 'p1.jpg' %>
      </div>

      <div class="donation-description p-l">
        <p class="title p-b">这里输入标题这里输入标题</p>
        <p class="date p-b">2016.5.1</p>
        <p class="state p-b">已完成</p>
      </div>

    </div>

    <div class="donation s-s p-t p-b p-l p-r">
      <div class="donation-pic ">
        <%= image_tag 'p1.jpg' %>
      </div>

      <div class="donation-description p-l">
        <p class="title p-b">这里输入标题这里输入标题</p>
        <p class="date p-b">2016.5.12</p>
        <p class="state p-b">审核中</p>
      </div>

    </div>

    <div class="donation s-s p-t p-b p-l p-r">
      <div class="donation-pic ">
        <%= image_tag 'p1.jpg' %>
      </div>

      <div class="donation-description p-l">
        <p class="title p-b">这里输入标题这里输入标题</p>
        <p class="date p-b">2016.5.5</p>
        <p class="state p-b">物流运输中</p>
      </div>

    </div>

  </div>

</div>

app/views/home/index.html.erb
<div class="homepage" id="homepage">
  <div class="carousel-swiper" id="carousel-swiper">
    <div class="swiper-container">
      <div class="swiper-wrapper">
        <% if @carousels != [] %>
          <% @carousels.each do |carousel| %>
            <% if carousel.is_custom == '1' %>
              <div class="swiper-slide">
                <%= link_to carousel.custom_url do %>
                  <%= image_tag carousel.image.to_s %>
                <% end %>
              </div>
            <% else %>
              <div class="swiper-slide">
                <%= link_to detail_carousel_path(carousel.id) do %>
                  <%= image_tag carousel.image.to_s %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <div class="swiper-slide">
            啊哦~~无轮播图
          </div>
        <% end %>

      </div>
      <div class="swiper-pagination"></div>
    </div>
  </div>

  <div class="rcmds s-s" id="rcmds">
    <div class="header-section p-l p-r">
      <p class="title">推荐</p>
      <a href="/shelf_items" class="all">查看全部 &nbsp;<i class="fa fa-angle-right fa-lg"></i></a>
    </div>

    <div class="shelf-items-wrapper">
      <ul class="shelf-items-list">
        <% @recommended_items.each do |p| %>
          <%= link_to shelf_item_path p.id do %>
            <li class="item">
              <%= image_tag p.thumb.to_s %>
              <div class="item-property p-b">
                <div class="item-name">
                  <%= p.product_name.to_s %>
                </div>
                <div class="item-bottom">
                  <div class="item-price red">
                    ¥<%= '%.2f' % p.price.to_s %>
                  </div>
                  <!--<div class="item-hearts t-right">-->
                    <!--<i class="fa fa-heart red"></i>&nbsp; 100-->
                  <!--</div>-->
                </div>
              </div>
            </li>
          <% end %>
        <% end %>

        <!--<div class="project-item m-t p-b">-->
        <!--<div class="project-pic">-->
        <!--<%#= image_tag 'p1.jpg' %>-->
        <!--</div>-->

        <!--<div class="project-info p-t p-b">-->
        <!--<p class="title">这里输入标题</p>-->

        <!--<p class="description">这里输入描述这里输入描述这里输入描述这里输入描述这里输入描述</p>-->

        <!--<div class="progress">-->
        <!--<div class="progress-bar">-->
        <!--<div class="green-bar"></div>-->
        <!--</div>-->
        <!--<div class="progress-percent">-->
        <!--<p>40%</p>-->
        <!--</div>-->
        <!--</div>-->

        <!--<div class="support-info">-->
        <!--<div class="supporters p-r">-->
        <!--<p class="total">20</p>-->

        <!--<p>支持人数</p>-->
        <!--</div>-->
        <!--<div class="money p-r">-->
        <!--<p class="total">5000</p>-->

        <!--<p>累计款项</p>-->
        <!--</div>-->
        <!--<div class="target p-r">-->
        <!--<p class="total">12500</p>-->

        <!--<p>目标</p>-->
        <!--</div>-->
        <!--</div>-->
        <!--</div>-->
        <!--</div>-->
      </ul>
    </div>
  </div>

  <div class="projects s-s p-b" id="projects">
    <div class="header-section p-l p-r">
      <p class="title">公益项目</p>
      <a href="/projects" class="all">查看全部 &nbsp;<i class="fa fa-angle-right fa-lg"></i></a>
    </div>

    <div class="project-list">
      <% @projects.each do |ele| %>
        <%= link_to detail_project_path ele.id do %>
          <div class="project-item m-b">
            <div class="project-pic">
              <%= image_tag ele.banner %>
            </div>
          </div>
        <% end %>
      <% end  %>
    </div>
  </div>

  <%= render template: 'shared/tabs' %>
</div>

<% content_for :title, set_title('GOODBUY公益商城') %>

<script>
  $(document).ready(function () {
    var swiper = new Swiper('.swiper-container', {
      pagination: '.swiper-pagination',
      paginationClickable: true,
      autoplay: 5000,
      loop: true
    });

    var host_url     =  'http://' + window.location.href.split('//')[1].split('/')[0] + '/';
    var current_url  = 'http://' + window.location.href.split('//')[1].split('/')[0];

    wx.ready(function () {
      wx.onMenuShareTimeline({
        title: 'GOODBUY公益商城', // 分享标题
        link: current_url,
        imgUrl: host_url + 'logo.png',
        success: function () {
          // 用户确认分享后执行的回调函数
        },
        cancel: function () {
          // 用户取消分享后执行的回调函数
        }
      });

      wx.onMenuShareAppMessage({
        title: 'GOODBUY公益商城', // 分享标题
        desc: '快来看看优秀的公益项目和创意新潮的产品吧', // 分享描述
        imgUrl: host_url + 'logo.png',
        link: current_url,
        success: function () {
          // 用户确认分享后执行的回调函数
        },
        cancel: function () {
          // 用户取消分享后执行的回调函数
        }
      });
    });
  })
</script>

app/views/home/my_address.html.erb
<div id="my-address" class="my-address">
  <div class="address-item p-l p-r p-t p-b">
    <p class="name">Name</p>

    <p class="tel">Telephone</p>

    <p class="address">address</p>
  </div>

  <div class="address-item p-l p-r p-t p-b">
    <p class="name">Name</p>

    <p class="tel">Telephone</p>

    <p class="address">address</p>
  </div>

</div>

<button class="btn btn-default btn-highlight m-l m-r p-t p-b">添加地址</button>

<div id="add-address-form" class="add-address-form">
  <%= form_for '', url: '', html: { class: 'form-horizontal' } do |f| %>
    <div class="form-group">
      <%= f.label :姓名, class: 'col-lg-1 control-label' %>
      <div class="col-lg-4"><%= f.text_field :name, class: 'col-lg-4 form-control', required: true %></div>
    </div>

    <div class="form-group">
      <%= f.label :手机号, class: 'col-lg-1 control-label' %>
      <div class="col-lg-4"><%= f.text_field :telephone, class: 'col-lg-4 form-control', required: true %></div>
    </div>

    <div class="form-group">
      <%= f.label :地址, class: 'col-lg-1 control-label' %>
      <div class="city-group">
        <select class="city-select">
          <option value="">--省份--</option>
          <%= options_for_select(ChinaCity.list) %>
        </select>

        <select class="city-select">
          <option value="">--城市--</option>
        </select>

        <select class="city-select">
          <option value="">--区县--</option>
        </select>
      </div>
      <div class="col-lg-4"><%= f.text_field :address, class: 'col-lg-4 form-control', required: true %></div>
    </div>

    <div class="form-group">
      <div class="col-lg-offset-1 col-lg-10">
        <%= f.submit '保存', class: "btn btn-sm btn-primary" %>
        &nbsp
        <%= link_to '返回', '#', class: "btn btn-sm btn-info", onclick: "history.back()" %>
      </div>
    </div>
  <% end %>

</div>

app/views/home/personal_center.html.erb
<div class="personal-center" id="personal-center">
  <div class="profile">
    <div class="avatar">
      <%= image_tag @user.headimgurl.to_s %>
    </div>
    <div class="wx_name">
      <p><%= @user.nickname.to_s %></p>
    </div>
    <div class="total-gyb">
      <%= link_to gybs_path do %>
        <p style="text-decoration: underline">
          <%= @user.gyb.to_s %>
        </p>
      <% end %>
      <p class="tt">公益币</p>
    </div>
  </div>

  <div class="menu">
    <%#= link_to do %>
    <!--<div class="my-cart s-s" id="my-cart">-->
    <!--<div class="t-left">-->
    <!--<i class="menu-icon fa fa-shopping-cart fa-lg"></i>-->

    <!--<p class="menu-name">我的购物车</p>-->
    <!--</div>-->
    <!--<div class="t-right">-->
    <!--<i class="arrow fa fa-angle-right fa-2x"></i>-->
    <!--</div>-->
    <!--<div class="clear"></div>-->
    <!--</div>-->
    <%# end %>

    <%= link_to gybs_path do %>
      <div class="my-gyb-menu s-s" id="my-gyb-menu">
        <div class="t-left">
          <i class="menu-icon fa fa-money fa-lg"></i>

          <p class="menu-name">我的公益币</p>
        </div>

        <div class="t-right">
          <i class="arrow fa fa-angle-right fa-2x"></i>
        </div>
        <div class="clear"></div>
      </div>
    <% end %>

    <%= link_to orders_path(:status => '0') do %>
      <div class="finished-orders s-s" id="finished-orders">
        <div class="t-left">
          <i class="menu-icon fa fa-bars fa-lg"></i>

          <p class="menu-name">未完成订单</p>
        </div>

        <div class="t-right">
          <i class="arrow fa fa-angle-right fa-2x"></i>
        </div>
        <div class="clear"></div>
      </div>
    <% end %>

    <%= link_to orders_path(:status => '1') do %>
      <div class="unfinished-orders" id="unfinished-orders">
        <div class="t-left">
          <i class="menu-icon fa fa-bars fa-lg"></i>

          <p class="menu-name">已完成订单</p>
        </div>

        <div class="t-right">
          <i class="arrow fa fa-angle-right fa-2x"></i>
        </div>
        <div class="clear"></div>
      </div>
    <% end %>

    <%= link_to orders_path(:status => '2') do %>
      <div class="after-sale-orders" id="after-sale-orders">
        <div class="t-left">
          <i class="menu-icon fa fa-bars fa-lg"></i>

          <p class="menu-name">退款/售后订单</p>
        </div>

        <div class="t-right">
          <i class="arrow fa fa-angle-right fa-2x"></i>
        </div>
        <div class="clear"></div>
      </div>
    <% end %>

    <%= link_to orders_path(:title => '所有订单') do %>
      <div class="all-orders" id="all-orders">
        <div class="t-left">
          <i class="menu-icon fa fa-bars fa-lg"></i>

          <p class="menu-name">所有订单</p>
        </div>

        <div class="t-right">
          <i class="arrow fa fa-angle-right fa-2x"></i>
        </div>
        <div class="clear"></div>
      </div>
    <% end %>

    <%= link_to supports_path do %>
      <div class="supported-projects s-s" id="supported-projects">
        <div class="t-left">
          <i class="menu-icon fa fa-heartbeat fa-lg"></i>

          <p class="menu-name">我支持的项目</p>
        </div>
        <div class="t-right">
          <i class="arrow fa fa-angle-right fa-2x"></i>
        </div>
        <div class="clear"></div>
      </div>
    <% end %>

    <%#= link_to do %>
      <!--<div class="my-donations s-s" id="my-donations">-->
        <!--<div class="t-left">-->
          <!--<i class="menu-icon fa fa-plus-circle fa-lg"></i>-->

          <!--<p class="menu-name">我的捐赠</p>-->
        <!--</div>-->
        <!--<div class="t-right">-->
          <!--<i class="arrow fa fa-angle-right fa-2x"></i>-->
        <!--</div>-->
        <!--<div class="clear"></div>-->
      <!--</div>-->
    <%# end %>

    <%= link_to addresses_path do %>
      <div class="my-settings s-s" id="my-settings">
        <div class="t-left">
          <i class="menu-icon fa fa-gears fa-lg"></i>

          <p class="menu-name">我的地址</p>
        </div>
        <div class="t-right">
          <i class="arrow fa fa-angle-right fa-2x"></i>
        </div>
        <div class="clear"></div>
      </div>
    <% end %>
  </div>

  <div class="foot m-t m-b p-t p-b">
    <p>&copy; 2017 Good Buy</p>
  </div>

</div>

<%= render template: 'shared/tabs' %>

<% content_for :title, set_title('我的') %>

app/views/home/project_detail.html.erb
<div class="project_detail" id="project_detail">
  <div class="project-detail-head">
    <%= image_tag 'project_pic.png' %>
  </div>

  <div class="project-title m-t m-b m-l p-l">这里是标题</div>

  <div class="progress">
    <div class="progress-bar">
      <div class="green-bar"></div>
    </div>
    <div class="progress-percent">
      <p>40%</p>
    </div>
  </div>

  <div class="support-info m-t m-b">
    <div class="supporters p-r">
      <p class="total">10</p>
      <p>无偿奉献爱心</p>
    </div>
    <div class="supporters p-r">
      <p class="total">10</p>
      <p>购买给予支持</p>
    </div>
    <div class="money p-r">
      <p class="total">5000</p>
      <p>累计款项</p>
    </div>
  </div>

  <div class="project-detail-area m-l m-r m-t m-b">
    <div class="cate-title-wrapper p-t p-b">
      <div class="cate-title p-l">
        <div class="p-bar"></div>
        <span class="p-title p-l">项目详情</span>
      </div>
    </div>
  </div>

  <div class="project-detail-area m-l m-r m-t m-b">
    <div class="cate-title-wrapper p-t p-b">
      <div class="cate-title p-l">
        <div class="p-bar"></div>
        <span class="p-title p-l">发起人</span>
      </div>
    </div>
  </div>

  <div class="project-detail-area m-l m-r m-t m-b">
    <div class="cate-title-wrapper p-t p-b">
      <div class="cate-title p-l">
        <div class="p-bar"></div>
        <span class="p-title p-l">支持者</span>
      </div>
    </div>

    <div class="project-supporters p-b">
      <div class="supporter-avatar m-t m-l">
        <%= image_tag 'avatar.jpg' %>
      </div>

      <div class="supporter-avatar m-t m-l">
        <%= image_tag 'avatar.jpg' %>
      </div>
    </div>

  </div>

  <div class="project-detail-area m-l m-r m-t m-b">
    <div class="cate-title-wrapper p-t p-b">
      <div class="cate-title p-l">
        <div class="p-bar"></div>
        <span class="p-title p-l">留言区</span>
      </div>
    </div>

    <div class="project-comment">
    </div>

  </div>

  <div class="btn-bottom-area">
    <button class="btn-default btn-highlight m-l m-r p-t p-b">无偿支持</button>
    <button class="btn-default m-l m-r p-t p-b">购买支持</button>
  </div>

</div>