config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount ChinaCity::Engine => '/china_city'

  devise_for :admin, controllers: {
  :sessions => "admin/sessions"
  }

  root 'home#index'

  resource :wechat, only: [:show, :create]

  resources :home, only: [:index] do
    get :personal_center,  on: :collection
    get :donations_center, on: :collection
    get :donate_page,      on: :collection
    get :my_address,       on: :collection
  end


  resources :carousels, only: [:detail] do
    get :detail, on: :member
  end

  get 'gybs' => 'gybs#index'
  get 'gybs/append'
  get 'gybs/exchange'

  resources :supports do
    get :detail, on: :collection
  end
  get '/supports/pay/:id', to: 'supports#pay', as: 'support_pay'

  resources :shelf_items
  get '/update_order_address' => 'shelf_items#update_order_address'

  resources :projects do
    member do
      get :detail
    end
  end

  get '/register', to: 'registrations#new'

  resources :donations
  resources :addresses do
    get :modify,      on: :collection
    get :set_default, on: :member
  end

  resources :orders do
    get :cancel_order,           on: :member
    get :apply_refund,           on: :member
    get :confirm_complete,       on: :member
    get :add_gyb_payment_record, on: :collection
    get :get_logistics_info, on: :collection
  end
  get '/orders/pay/:id', to: 'orders#pay', as: 'order_pay'

  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      get '/login', to: 'login#index'

      get '/shelf_items', to: 'shelf_items#index'
      get '/shelf_items/get_shelf_item', to: 'shelf_items#get_shelf_item'
      get '/shelf_items/get_linked_project', to: 'shelf_items#get_linked_project'

      get '/projects', to: 'projects#index'
      get '/projects/get_project', to: 'projects#get_project', as: 'get_project'
      get '/projects/get_linked_shelf_items', to: 'projects#get_linked_shelf_items'

      get '/carousels', to: 'carousels#index'

      get '/gybs/get_gyb_income_records', to: 'gybs#get_gyb_income_records'
      get '/gybs/get_gyb_payment_records', to: 'gybs#get_gyb_payment_records'

      get '/addresses/get_addresses', to: 'addresses#get_addresses'
      get '/addresses/get_address', to: 'addresses#get_address'
      get '/addresses/get_default_address', to: 'addresses#get_default_address'
      post '/addresses/create_address', to: 'addresses#create_address'
      delete '/addresses/delete_address', to: 'addresses#delete_address'
      post '/addresses/set_default', to: 'addresses#set_default'
    end
  end

  namespace :admin do
    get 'dashboard' => 'home#index'

    resources :users

    resources :carousels do
      get :preview,   on: :member
      get :publish,   on: :member
      get :depublish, on: :member
    end

    resources :products do
      get :preview, on: :member
    end

    resources :gybs

    resources :shelf_items do
      get :pull_off_shelf,    on: :member
      get :set_recommended,   on: :member
      get :reset_recommended, on: :member
      collection do
        get :on_shelf_list
        get :off_shelf_list
        get :recommended_list
      end
    end

    resources :product_categories
    resources :product_labels

    resources :projects do
      member do
        get :preview
        get :publish
        get :depublish
        get :recommend
        get :reset_recommend
      end
      collection do
        get :all
        get :recommended_projects
        get :get_supports
      end
    end

    resources :donations

    resources :orders do
      collection do
        post :update
        get :query
        get :refund_orders
        get :undelivered_orders
        post :get_excel, :defaults => { :format => 'xlsx' }
      end

      get :refund_process, on: :member
    end
  end

  get '/init_js_info', to: 'init_js_info#init_js_info'

  scope 'wepay' do
    get '/jsapi/',          to: 'wepay#recv'
    get '/unified_order',   to: 'wepay#unified_order'
    get '/refund_order',    to: 'wepay#refund_order'
    get '/init_wx_js_info', to: 'wepay#init_wx_js_info'
    get '/init_jspay_info', to: 'wepay#init_jspay_info'
    get '/get_logistics',   to: 'wepay#get_logistics'
    post '/notify',         to: 'wepay#notify'
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  self.primary_key= 'project_id'

  mount_uploader :thumb,    ProjectThumbUploader
  mount_uploader :banner,   ProjectBannerUploader
  mount_uploader :main_pic, ProjectMainPicUploader

  has_many :supports
  # has_many :users, through: :supports

  has_many :shelf_items

  # enum type: { 'TYPE1': 1, 'TYPE2': 2 }
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AuthenticatedController
  def all
    respond_to do |format|
      format.html
      format.json { get_rows(0) }
    end
  end

  def get_supports
    respond_to do |format|
      format.html
      format.json { get_supports_rows }
    end
  end

  def recommended_projects
    respond_to do |format|
      format.html
      format.json { get_rows(1) }
    end
  end

  def new
    @not_linked_items = ShelfItem.where('project_id IS NULL and is_on_shelf = ?', '1')
    if @not_linked_items != []
      @project = Project.new
    else
      render text: '啊哦～～不存在多余的可关联的商品。请先添加商品。'
    end
  end

  def edit
    @project               = Project.find params[:id]
    @not_linked_items      = ShelfItem.where(project_id: nil, is_on_shelf: '1')
    @items_of_this_project = ShelfItem.where('project_id = ? and is_on_shelf = ?', params[:id], '1')
  end

  def create
    create_or_update project_params
  end

  def update
    create_or_update params[:id], project_params
  end

  def destroy
    project = Project.find params[:id]
    redirect_to all_admin_projects_path if project.destroy
  end

  def preview
    id       = params[:id]
    @project = Project.find_by_project_id(id)
    render layout: 'application'
  end

  def publish
    id      = params[:id]
    project = Project.find_by_project_id(id)
    if project
      project.update_attribute(:is_published, '1')
      redirect_to all_admin_projects_path
    end
  end

  def depublish
    id = params[:id]
    project = Project.find_by_project_id(id)
    if project
      project.update_attributes(:is_published => '0', :is_recommended => '0')
      redirect_to all_admin_projects_path
    else
      render plain: '出错啦～～'
    end
  end

  def recommend
    id      = params[:id]
    project = Project.find_by_project_id(id)
    if project
      project.update_attribute(:is_recommended, '1')
    end
    redirect_to all_admin_projects_path
  end

  def reset_recommend
    id      = params[:id]
    project = Project.find_by_project_id(id)
    if project
      project.update_attribute(:is_recommended, '0')
    end
    redirect_to recommended_projects_admin_projects_path
  end

  private
  def get_rows(filter)
    dt = decode_datatables_params

    where_array = []

    if filter == 1
      where_array << "is_recommended = '1'"
    end

    search_obj = {
        :include => [],
        :joins => [],
        :order => dt[:sort_statement],
        :conditions => [where_array.join(' AND ')]
    }

    @total_rows = Project.count(search_obj)
    @rows = Project.page(dt[:page]).per(dt[:per_page])
                .includes(search_obj[:include])
                .joins(search_obj[:joins])
                .order(search_obj[:order])
                .where(search_obj[:conditions])
  end

  def get_supports_rows
    dt = decode_datatables_params

    where_array = []
    where_array << "status = '1'"

    search_obj = {
      :include => [],
      :joins => [],
      :order => dt[:sort_statement],
      :conditions => [where_array.join(' AND ')]
    }

    @total_rows = Support.count(search_obj)
    @rows = Support.page(dt[:page]).per(dt[:per_page])
              .includes(search_obj[:include])
              .joins(search_obj[:joins])
              .order(search_obj[:order])
              .where(search_obj[:conditions])
  end

  def create_or_update(id = 0, data)
    ##################################################
    # Still remains lots of problems in this action. #
    ##################################################

    shelf_item_ids = params[:project][:shelf_item_ids]
    if id == 0
      project = Project.new data.except(:shelf_item_ids)
      project.project_id = generate_unique_id
      if shelf_item_ids
        shelf_item_ids.each do |_id|
          if _id[1] != ''
            shelf_item = ShelfItem.find_by(:id => _id[1])
            # binding.pry
            shelf_item.project_id = data[:project_id] if shelf_item
            shelf_item.save if shelf_item
          end
        end
      end
      redirect_to all_admin_projects_path if project.save
    else
      project = Project.find(id)
      if shelf_item_ids
        shelf_item_ids.each do |_id|
          if _id[1] != ''
            shelf_item = ShelfItem.find_by(:id => _id[1])
            shelf_item.update_attribute(:project_id, project.project_id)
          end
        end
      end
      redirect_to all_admin_projects_path if project.update_attributes data.except(:shelf_item_ids)
    end
  end

  def generate_unique_id
    'P1' + SecureRandom.random_number(999999).to_s
  end

  def project_params
    params.require(:project).permit(:project_name, :category, :banner, :main_pic, :thumb, :project_type_id, :goal,
                                    :project_detail, :support_type_id, shelf_item_ids: [:shelf_item_id_1, :shelf_item_id_2, :shelf_item_id_3])
  end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < ApplicationController
  def index
    param = params[:param]
    if param == 'recommended'
      projects = Project.where('is_published = ? and is_recommended = ?', '1', '1')
      render json: projects, status: :ok
    else
      projects = Project.where('is_published = ?', '1')
      render json: projects, status: :ok
    end
  end

  def get_project
    pid = params[:pid]
    if pid
      project = Project.find_by(:project_id => pid)
      render json: project, status: :ok if project
    end
  end

  def get_linked_shelf_items
    pid = params[:pid]
    if pid
      shelf_items = ShelfItem.where('is_on_shelf = ? and project_id = ?', '1', pid)
      render json: shelf_items, status: :ok
    else
      render json: { data: 'no request params.' }
    end

  end
end

app/controllers/projects_controller.rb
class ProjectsController < BaseController
  def index
    @projects = Project.where('is_published = ?', '1').order('updated_at DESC')
  end

  def detail
    id = params[:id]
    @project = Project.find_by_project_id(id)
    @shelf_items = ShelfItem.where('project_id = ? and is_on_shelf = ?', id, '1')

    @total, @num_dedication_support, @num_purchase_support, @percent, @support_count, total_dedication_support = 0, 0, 0, 0, 0, 0
    @price_gap = '498'
    @supports  = Support.where('project_id = ? and status = ?', id, '1')

    if @supports != []
      @supports.each do |ele|
        if ele.money and ele.support_type == '0'
          @total                    += ele.money
          total_dedication_support  += ele.money
          @num_dedication_support   += ele.count
          @support_count            += (total_dedication_support / 49800).to_i
        elsif ele.support_type == '1'
          @total                    += ele.money
          @num_purchase_support     += ele.count
          @support_count            += @num_purchase_support
        end
      end
      # @percent = @total.to_f / @project.goal.to_f
      @price_gap = 498 - (total_dedication_support.to_f % 49800.0) / 100
      @percent   = (total_dedication_support % 49800.0).to_f / 49800.0
    end
  end
end

app/views/admin/projects/_form.html.erb
<%= form_for @project, url: url, html: {class: 'form-horizontal'} do |f| %>
  <div class="form-group">
    <%= f.label :project_name, class: 'col-lg-1 control-label' %>
    <div class="col-lg-4"><%= f.text_field :project_name, class: 'col-lg-4 form-control', required: true %></div>
  </div>

  <div class="form-group">
    <%= f.label :category, class: 'col-lg-1 control-label' %>
    <% if @project.category.blank? %>
      <div class="col-lg-4"><%= f.select :category, options_for_select([["类别1", "1"], ["类别2", "2"]]), {prompt: '-- select one --'}, {class: 'col-lg-4 form-control', required: true} %></div>
    <% else %>
      <div class="col-lg-4"><%= f.select :category, options_for_select([["类别1", "1"], ["类别2", "2"]], selected: "#{@project.category}"), {prompt: '-- select one --'}, {class: 'col-lg-4 form-control'} %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :thumb, class: 'col-lg-1 control-label' %>
    <% if @project.thumb.blank? %>
      <div class="col-lg-4"><%= f.file_field :thumb, class: 'col-lg-4 form-control', required: true %></div>
    <% else %>
      <div><%= render_img @project.thumb, :width => '200px', :height => '50px', :style => 'margin-left: 14px; margin-bottom: 14px;' %></div>
      <div class="col-lg-4 col-lg-offset-1"><%= f.file_field :thumb, class: 'form-control' %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :banner, class: 'col-lg-1 control-label' %>
    <% if @project.banner.blank? %>
      <div class="col-lg-4"><%= f.file_field :banner, class: 'col-lg-4 form-control', required: true %></div>
    <% else %>
      <div><%= render_img @project.banner, :width => '200px', :height => '50px', :style => 'margin-left: 14px; margin-bottom: 14px;' %></div>
      <div class="col-lg-4 col-lg-offset-1"><%= f.file_field :banner, class: 'form-control' %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :main_pic, class: 'col-lg-1 control-label' %>
    <% if @project.main_pic.blank? %>
      <div class="col-lg-4"><%= f.file_field :main_pic, class: 'col-lg-4 form-control', required: true %></div>
    <% else %>
      <div><%= render_img @project.main_pic, :width => '200px', :height => '50px', :style => 'margin-left: 14px; margin-bottom: 14px;' %></div>
      <div class="col-lg-4 col-lg-offset-1"><%= f.file_field :main_pic, class: 'form-control' %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :关联商品, class: 'col-lg-1 control-label' %>
    <% if @items_of_this_project %>
      <div class="col-lg-10">
        <% @items_of_this_project.each do |item| %>
          <div style="margin-bottom: 14px; display: inline-block"><%= render_img item.thumb, :width => '80px', :height => '80px' %></div>
        <% end %>
      </div>
    <% end %>

    <% if @not_linked_items  %>
      <div class="col-lg-9 col-lg-offset-1">
        <%= f.fields_for :shelf_item_ids do |item| %>
          <div class="col-lg-3"><%= item.collection_select :shelf_item_id_1, @not_linked_items, :id, :product_name, {prompt: '-- select one --'}, {id: 'item1'} %></div>
          <div class="col-lg-3"><%= item.collection_select :shelf_item_id_2, @not_linked_items, :id, :product_name, {prompt: '-- select one --'}, {id: 'item2'} %></div>
          <div class="col-lg-3"><%= item.collection_select :shelf_item_id_3, @not_linked_items, :id, :product_name, {prompt: '-- select one --'}, {id: 'item3'} %></div>
        <% end %>
      </div>

    <% else %>
      <%# binding.pry %>
      <div class="col-lg-10 col-lg-offset-1">不存在多余的可关联的商品。</div>
    <% end %>

    <!--<div id="add-shelf-item-btn" class="col-lg-1">-->
    <!--<i class="fa fa-2x fa-plus"></i>-->
    <!--</div>-->
  </div>

  <div class="form-group">
    <%= f.label :goal, class: 'col-lg-1 control-label' %>
    <div class="col-lg-4"><%= f.text_field :goal, class: 'col-lg-4 form-control', required: true %></div>
  </div>

  <div class="form-group">
    <%= f.label :project_detail, class: 'col-lg-1 control-label' %>
    <div class="col-lg-11"><%= f.cktext_area :project_detail, required: true %></div>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-1 col-lg-10">
      <%= f.submit '保存', class: "btn btn-sm btn-primary" %>
      &nbsp
      <%= link_to '返回', '#', class: "btn btn-sm btn-info", onclick: "history.back()" %>
    </div>
  </div>
<% end %>

app/views/admin/projects/all.html.erb
<div class="nav-content-head">
  <ul class="breadcrumb">
    <li><span class="primary-font"><i class="icon-home"></i></span><a href="/admin/dashboard"> 首页</a></li>
    <li>项目管理</li>
    <li>全部项目</li>
  </ul>
  <%= link_to new_admin_project_path, class: 'btn-new btn btn-primary marginTB-xs' do %>
      <i class="fa fa-plus m-right-xs"></i>New Project
  <% end %>
</div>

<div class="wrapper-md">
  <div class="panel panel-default">
    <div class="table-responsive">
      <%= dt id: 'projects_datatable', class: 'table table-striped b-t b-b', :'data-url' => all_admin_projects_path(:format => :json)  do %>
          <%= dt_col(Project.hn(:project_id), data: { data: 'project_id' }) %>
          <%= dt_col(Project.hn(:project_name), data: { data: 'project_name' }) %>
          <%= dt_col(Project.hn(:thumb), data: { data: 'thumb' }) %>
          <%= dt_col(Project.hn(:banner), data: { data: 'banner' }) %>
          <%= dt_col(Project.hn(:main_pic), data: { data: 'main_pic' }) %>
          <%= dt_col(Project.hn(:category), data: { data: 'category' }) %>
          <%= dt_col(Project.hn(:goal), data: { data: 'goal' }) %>
          <%= dt_col(Project.hn(:created_at), data: { data: 'created_at' }) %>
          <%= dt_col(Project.hn(:action), data: { data: 'actions' }) %>
          <%= dt_col(Project.hn(:more_actions), data: { data: 'more_actions' }) %>
      <% end %>
    </div>
  </div>
</div>

<% content_for :scripts do %>
  <%= controller_js_include %>
<% end %>

app/views/admin/projects/edit.html.erb
<div class="wrapper-lg">
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading h5">项目编辑</div>
        <div class="panel-body">
          <%= render partial: 'form', locals: { url: admin_project_path } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/projects/get_supports.html.erb
<div class="nav-content-head">
  <ul class="breadcrumb">
    <li><span class="primary-font"><i class="icon-home"></i></span><a href="/admin/dashboard"> 首页</a></li>
    <li>项目管理</li>
    <li>项目支持</li>
  </ul>
</div>

<div class="wrapper-md">
  <div class="panel panel-default">
    <div class="table-responsive">
      <%= dt id: 'get_supports_datatable', class: 'table table-striped b-t b-b', :'data-url' => get_supports_admin_projects_path(:format => :json)  do %>
        <%= dt_col(Support.hn(:id), data: { data: 'id' }) %>
        <%= dt_col(Support.hn(:project_name), data: { data: 'project_name' }) %>
        <%= dt_col(Support.hn(:project_id), data: { data: 'project_id' }) %>
        <%= dt_col(Support.hn(:user_id), data: { data: 'user_id' }) %>
        <%= dt_col(Support.hn(:support_type), data: { data: 'support_type' }) %>
        <%= dt_col(Support.hn(:money), data: { data: 'money' }) %>
        <%= dt_col(Support.hn(:order_detail_id), data: { data: 'order_detail_id' }) %>
        <%= dt_col(Support.hn(:created_at), data: { data: 'created_at' }) %>
      <% end %>
    </div>
  </div>
</div>

<% content_for :scripts do %>
  <%= controller_js_include %>
<% end %>

app/views/admin/projects/index.html.erb
<div class="nav-content-head">
  <ul class="breadcrumb">
    <li><span class="primary-font"><i class="icon-home"></i></span><a href="/admin/home"> Home</a></li>
    <li>项目管理</li>
    <li>全部项目</li>
  </ul>
  <%= link_to new_admin_project_path, class: 'btn-new btn btn-primary marginTB-xs' do %>
      <i class="fa fa-plus m-right-xs"></i>New Project
  <% end %>
</div>

<div class="wrapper-md">
  <div class="panel panel-default">
    <div class="table-responsive">
      <%= dt id: 'projects_datatable', class: 'table table-striped b-t b-b', :'data-url' => admin_projects_path(:format => :json)  do %>
          <%= dt_col(Project.hn(:project_id), data: { data: 'project_id' }) %>
          <%= dt_col(Project.hn(:project_name), data: { data: 'project_name' }) %>
          <%= dt_col(Project.hn(:thumb), data: { data: 'thumb' }) %>
          <%= dt_col(Project.hn(:banner), data: { data: 'banner' }) %>
          <%= dt_col(Project.hn(:main_pic), data: { data: 'main_pic' }) %>
          <%= dt_col(Project.hn(:category), data: { data: 'category' }) %>
          <%= dt_col(Project.hn(:goal), data: { data: 'goal' }) %>
          <%= dt_col(Project.hn(:created_at), data: { data: 'created_at' }) %>
          <%= dt_col(Project.hn(:action), data: { data: 'actions' }) %>
          <%= dt_col(Project.hn(:more_actions), data: { data: 'more_actions' }) %>
      <% end %>
    </div>
  </div>
</div>

<% content_for :scripts do %>
  <%= controller_js_include %>
<% end %>

app/views/admin/projects/new.html.erb
<div class="wrapper-lg">
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default">
        <div class="panel-heading h5">新增项目</div>
        <div class="panel-body">
          <%= render partial: 'form', locals: { url: admin_projects_path, back_url: all_admin_projects_path } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/projects/preview.html.erb
<div class="preview">
  <div class="project_detail" id="project_detail">
    <div class="project-detail-head">
      <%= image_tag @project.main_pic.to_s %>
    </div>

    <div class="project-title m-t m-b m-l p-l"><%= @project.project_name.to_s %></div>

    <div class="progress">
      <div class="progress-bar">
        <div class="green-bar"></div>
      </div>
      <div class="progress-percent">
        <p>40%</p>
      </div>
    </div>

    <div class="support-info m-t m-b">
      <div class="supporters p-r">
        <p class="total">10</p>
        <p>无偿奉献爱心</p>
      </div>
      <div class="supporters p-r">
        <p class="total">10</p>
        <p>购买给予支持</p>
      </div>
      <div class="money p-r">
        <p class="total">5000</p>
        <p>累计款项</p>
      </div>
    </div>

    <div class="project-detail-area m-l m-r m-t m-b">
      <div class="cate-title-wrapper p-t p-b">
        <div class="cate-title p-l">
          <div class="p-bar"></div>
          <span class="p-title p-l">项目详情</span>
        </div>
      </div>
      <div class="detail-body p-t p-b p-l p-r">
        <%= @project.project_detail.html_safe.to_s %>
      </div>
    </div>

    <div class="btn-bottom-area">
      <button class="btn-default btn-highlight m-l m-r p-t p-b" id="dedicate-btn">无偿支持</button>
      <button class="btn-default m-l m-r p-t p-b" id="purchase-btn">购买支持</button>
    </div>

  </div>
</div>

<% content_for :title, '项目详情' %>

app/views/admin/projects/recommended_projects.html.erb
<div class="nav-content-head">
  <ul class="breadcrumb">
    <li><span class="primary-font"><i class="icon-home"></i></span><a href="/admin/dashboard"> 首页</a></li>
    <li>项目管理</li>
    <li>推荐位项目</li>
  </ul>
</div>

<div class="wrapper-md">
  <div class="panel panel-default">
    <div class="table-responsive">
      <%= dt id: 'recommended_projects_datatable', class: 'table table-striped b-t b-b', :'data-url' => recommended_projects_admin_projects_path(:format => :json)  do %>
        <%= dt_col(Project.hn(:project_id), data: { data: 'project_id' }) %>
        <%= dt_col(Project.hn(:project_name), data: { data: 'project_name' }) %>
        <%= dt_col(Project.hn(:thumb), data: { data: 'thumb' }) %>
        <%= dt_col(Project.hn(:banner), data: { data: 'banner' }) %>
        <%= dt_col(Project.hn(:main_pic), data: { data: 'main_pic' }) %>
        <%= dt_col(Project.hn(:category), data: { data: 'category' }) %>
        <%= dt_col(Project.hn(:goal), data: { data: 'goal' }) %>
        <%= dt_col(Project.hn(:created_at), data: { data: 'created_at' }) %>
        <%= dt_col(Project.hn(:more_actions), data: { data: 'more_actions' }) %>
      <% end %>
    </div>
  </div>
</div>

<% content_for :scripts do %>
  <%= controller_js_include %>
<% end %>